### ISSUE TITLE
Module requires the server to be already started, and does not react to server restarts.

### ISSUE THREAD

**Issue by nexylmao** [Wolkabout/WolkGatewayModule-Modbus#21]
There are two cases where the module doesn't work as expected:

1. When you start the module, you already need to have a Modbus TCP Server started. If it's not started, it will never catch a connection to it, and you must restart the module, to catch the connection.
2. When you finally start the module (after the server), it does not react to server restarts. If it loses the connection, it will never reconnect to the server. It will just loop infinitely while logging "Unable to read * on slave * from address '*'"

**Comment by milanzlicic** [comment]
Fixed
